name: Docker Image Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Configure Docker
      run: |
        echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
        sudo service docker restart
    - name: Build the Docker image
      run: docker build . --squash --file Dockerfile --tag meyskens/vscode-maartje:latest
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
    - name: Log in to registry
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u "meyskens" --password-stdin
    - name: Push image
      run: docker push meyskens/vscode-maartje:latest
